"""FormattingSkill — structural formatting (fallthrough-only, no widget)."""

import re
import logging
from ..base import Skill, SkillResult

logger = logging.getLogger(__name__)

# Format types we can detect from the query
FORMAT_PATTERNS = {
    "bullets": r"\b(bullet points?|bulleted list)\b",
    "numbered": r"\b(numbered list|ordered list|steps)\b",
    "outline": r"\b(outline)\b",
    "table": r"\b(table of|as a table|into a table|tabular)\b",
}


def _detect_format_type(query: str) -> str:
    """Detect the requested output format."""
    q = query.lower()
    for fmt, pattern in FORMAT_PATTERNS.items():
        if re.search(pattern, q):
            return fmt
    return "bullets"  # default


def _extract_content(query: str, context: dict) -> str | None:
    """Extract inline content to format, if present."""
    return context.get("content")


class FormattingSkill(Skill):
    name = "formatting"
    description = "Structural formatting (bullets, numbered lists, outlines, tables)"
    triggers = [
        r"\b(bullet points?|numbered list|outline for|table of)\b",
        r"\b(format|organize|structure)\b.{0,20}\b(as|into)\b.{0,20}\b(list|bullets|table)\b",
    ]

    def __init__(self, config: dict = None):
        self._config = config or {}
        self._max_items = self._config.get("max_items", 50)

    def is_available(self) -> bool:
        return True

    async def execute(self, query: str, context: dict) -> SkillResult:
        fmt = _detect_format_type(query)
        content = _extract_content(query, context)

        # Content must be generated by the LLM — fallthrough with format hint
        # Director will inject the format constraint into the system prompt
        return SkillResult(
            success=True,
            skill_name=self.name,
            fallthrough=True,
            result_str=f"format:{fmt}",
            data={"format_type": fmt, "max_items": self._max_items},
        )

    def narration_hint(self, result: SkillResult) -> str:
        fmt = result.data.get("format_type", "list") if result.data else "list"
        return (
            f"Format response as {fmt}. "
            "Keep the structure clean and scannable."
        )
